// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dtap.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DTAP module

	/**
	* Works with enumarations: 
	* - ENU_Environment
	* - ENU_DTAP_Level
	* 
	* And microflows:
	* - ACT_RetrieveCurrentDTAP
	* - ACT_RetrieveCurrentDTAP_Level
	* 
	* Corresponds to levels:
	* 0 = Development
	* 1 = Test and below
	* 2 = Acceptance and below
	* 3 = Performance and below
	* 4 = Reporting and below
	* 5 = Production and below
	*/
	public static java.lang.String getDTAPMode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DTAP.DTAPMode");
	}
}