// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dtap.proxies;

public class DTAPInformation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dTAPInformationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DTAP.DTAPInformation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DTAPLevel("DTAPLevel"),
		CurrentEnvironment("CurrentEnvironment"),
		DTAPLevelAsInteger("DTAPLevelAsInteger"),
		ApplicationURL("ApplicationURL"),
		LastUpdatedOn("LastUpdatedOn"),
		MendixVersion("MendixVersion"),
		ModelVersion("ModelVersion"),
		ShowEnvironmentInformation("ShowEnvironmentInformation");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DTAPInformation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DTAP.DTAPInformation"));
	}

	protected DTAPInformation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dTAPInformationMendixObject)
	{
		if (dTAPInformationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DTAP.DTAPInformation", dTAPInformationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DTAP.DTAPInformation");

		this.dTAPInformationMendixObject = dTAPInformationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DTAPInformation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static dtap.proxies.DTAPInformation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return dtap.proxies.DTAPInformation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static dtap.proxies.DTAPInformation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dtap.proxies.DTAPInformation(context, mendixObject);
	}

	public static dtap.proxies.DTAPInformation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dtap.proxies.DTAPInformation.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of DTAPLevel
	 * @param dtaplevel
	 */
	public final dtap.proxies.ENU_DTAP_Level getDTAPLevel()
	{
		return getDTAPLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of DTAPLevel
	 */
	public final dtap.proxies.ENU_DTAP_Level getDTAPLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DTAPLevel.toString());
		if (obj == null)
			return null;

		return dtap.proxies.ENU_DTAP_Level.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DTAPLevel
	 * @param dtaplevel
	 */
	public final void setDTAPLevel(dtap.proxies.ENU_DTAP_Level dtaplevel)
	{
		setDTAPLevel(getContext(), dtaplevel);
	}

	/**
	 * Set value of DTAPLevel
	 * @param context
	 * @param dtaplevel
	 */
	public final void setDTAPLevel(com.mendix.systemwideinterfaces.core.IContext context, dtap.proxies.ENU_DTAP_Level dtaplevel)
	{
		if (dtaplevel != null)
			getMendixObject().setValue(context, MemberNames.DTAPLevel.toString(), dtaplevel.toString());
		else
			getMendixObject().setValue(context, MemberNames.DTAPLevel.toString(), null);
	}

	/**
	 * Set value of CurrentEnvironment
	 * @param currentenvironment
	 */
	public final dtap.proxies.ENU_Environment getCurrentEnvironment()
	{
		return getCurrentEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentEnvironment
	 */
	public final dtap.proxies.ENU_Environment getCurrentEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CurrentEnvironment.toString());
		if (obj == null)
			return null;

		return dtap.proxies.ENU_Environment.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CurrentEnvironment
	 * @param currentenvironment
	 */
	public final void setCurrentEnvironment(dtap.proxies.ENU_Environment currentenvironment)
	{
		setCurrentEnvironment(getContext(), currentenvironment);
	}

	/**
	 * Set value of CurrentEnvironment
	 * @param context
	 * @param currentenvironment
	 */
	public final void setCurrentEnvironment(com.mendix.systemwideinterfaces.core.IContext context, dtap.proxies.ENU_Environment currentenvironment)
	{
		if (currentenvironment != null)
			getMendixObject().setValue(context, MemberNames.CurrentEnvironment.toString(), currentenvironment.toString());
		else
			getMendixObject().setValue(context, MemberNames.CurrentEnvironment.toString(), null);
	}

	/**
	 * @return value of DTAPLevelAsInteger
	 */
	public final java.lang.Integer getDTAPLevelAsInteger()
	{
		return getDTAPLevelAsInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of DTAPLevelAsInteger
	 */
	public final java.lang.Integer getDTAPLevelAsInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DTAPLevelAsInteger.toString());
	}

	/**
	 * Set value of DTAPLevelAsInteger
	 * @param dtaplevelasinteger
	 */
	public final void setDTAPLevelAsInteger(java.lang.Integer dtaplevelasinteger)
	{
		setDTAPLevelAsInteger(getContext(), dtaplevelasinteger);
	}

	/**
	 * Set value of DTAPLevelAsInteger
	 * @param context
	 * @param dtaplevelasinteger
	 */
	public final void setDTAPLevelAsInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dtaplevelasinteger)
	{
		getMendixObject().setValue(context, MemberNames.DTAPLevelAsInteger.toString(), dtaplevelasinteger);
	}

	/**
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL()
	{
		return getApplicationURL(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationURL
	 */
	public final java.lang.String getApplicationURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationURL.toString());
	}

	/**
	 * Set value of ApplicationURL
	 * @param applicationurl
	 */
	public final void setApplicationURL(java.lang.String applicationurl)
	{
		setApplicationURL(getContext(), applicationurl);
	}

	/**
	 * Set value of ApplicationURL
	 * @param context
	 * @param applicationurl
	 */
	public final void setApplicationURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationurl)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationURL.toString(), applicationurl);
	}

	/**
	 * @return value of LastUpdatedOn
	 */
	public final java.util.Date getLastUpdatedOn()
	{
		return getLastUpdatedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of LastUpdatedOn
	 */
	public final java.util.Date getLastUpdatedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastUpdatedOn.toString());
	}

	/**
	 * Set value of LastUpdatedOn
	 * @param lastupdatedon
	 */
	public final void setLastUpdatedOn(java.util.Date lastupdatedon)
	{
		setLastUpdatedOn(getContext(), lastupdatedon);
	}

	/**
	 * Set value of LastUpdatedOn
	 * @param context
	 * @param lastupdatedon
	 */
	public final void setLastUpdatedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastupdatedon)
	{
		getMendixObject().setValue(context, MemberNames.LastUpdatedOn.toString(), lastupdatedon);
	}

	/**
	 * @return value of MendixVersion
	 */
	public final java.lang.String getMendixVersion()
	{
		return getMendixVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of MendixVersion
	 */
	public final java.lang.String getMendixVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MendixVersion.toString());
	}

	/**
	 * Set value of MendixVersion
	 * @param mendixversion
	 */
	public final void setMendixVersion(java.lang.String mendixversion)
	{
		setMendixVersion(getContext(), mendixversion);
	}

	/**
	 * Set value of MendixVersion
	 * @param context
	 * @param mendixversion
	 */
	public final void setMendixVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mendixversion)
	{
		getMendixObject().setValue(context, MemberNames.MendixVersion.toString(), mendixversion);
	}

	/**
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion()
	{
		return getModelVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelVersion.toString());
	}

	/**
	 * Set value of ModelVersion
	 * @param modelversion
	 */
	public final void setModelVersion(java.lang.String modelversion)
	{
		setModelVersion(getContext(), modelversion);
	}

	/**
	 * Set value of ModelVersion
	 * @param context
	 * @param modelversion
	 */
	public final void setModelVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelversion)
	{
		getMendixObject().setValue(context, MemberNames.ModelVersion.toString(), modelversion);
	}

	/**
	 * @return value of ShowEnvironmentInformation
	 */
	public final java.lang.Boolean getShowEnvironmentInformation()
	{
		return getShowEnvironmentInformation(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowEnvironmentInformation
	 */
	public final java.lang.Boolean getShowEnvironmentInformation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowEnvironmentInformation.toString());
	}

	/**
	 * Set value of ShowEnvironmentInformation
	 * @param showenvironmentinformation
	 */
	public final void setShowEnvironmentInformation(java.lang.Boolean showenvironmentinformation)
	{
		setShowEnvironmentInformation(getContext(), showenvironmentinformation);
	}

	/**
	 * Set value of ShowEnvironmentInformation
	 * @param context
	 * @param showenvironmentinformation
	 */
	public final void setShowEnvironmentInformation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showenvironmentinformation)
	{
		getMendixObject().setValue(context, MemberNames.ShowEnvironmentInformation.toString(), showenvironmentinformation);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dTAPInformationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dtap.proxies.DTAPInformation that = (dtap.proxies.DTAPInformation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DTAP.DTAPInformation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
