// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dtap.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DTAP module
	public static void aCT_DTAPInformation_ShowExample(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("DTAP.ACT_DTAPInformation_ShowExample").withParams(params).execute(context);
	}
	public static boolean aSU_DTAPInitialize(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("DTAP.ASU_DTAPInitialize").withParams(params).execute(context);
	}
	public static dtap.proxies.DTAPInformation dS_DTAPInformation(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DTAP.DS_DTAPInformation").withParams(params).execute(context);
		return result == null ? null : dtap.proxies.DTAPInformation.initialize(context, result);
	}
	public static dtap.proxies.DTAPInformation dTAPInformation_GetCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DTAP.DTAPInformation_GetCreate").withParams(params).execute(context);
		return result == null ? null : dtap.proxies.DTAPInformation.initialize(context, result);
	}
	public static java.lang.String dTAPInformation_RetrieveApplicationURL(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("DTAP.DTAPInformation_RetrieveApplicationURL").withParams(params).execute(context);
	}
	public static dtap.proxies.ENU_DTAP_Level dTAPInformation_RetrieveCurrentDTAP_Level(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.lang.String result = (java.lang.String) Core.microflowCall("DTAP.DTAPInformation_RetrieveCurrentDTAP_Level").withParams(params).execute(context);
		return result == null ? null : dtap.proxies.ENU_DTAP_Level.valueOf(result);
	}
	public static java.lang.Long dTAPInformation_RetrieveCurrentDTAP_Level_AsInteger(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Long) Core.microflowCall("DTAP.DTAPInformation_RetrieveCurrentDTAP_Level_AsInteger").withParams(params).execute(context);
	}
	public static dtap.proxies.ENU_Environment dTAPInformation_RetrieveCurrentEnvironment(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.lang.String result = (java.lang.String) Core.microflowCall("DTAP.DTAPInformation_RetrieveCurrentEnvironment").withParams(params).execute(context);
		return result == null ? null : dtap.proxies.ENU_Environment.valueOf(result);
	}
}